# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitpad" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "afd08eacee9c534e92e6e8a759d8d5ee3cf22574b5258474ab7d4ca0d65ff9cc"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b0581352c9eb3d0c85ae1a2d8df7489de3dc236e47ebe93c1cd7b308ae83e92"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d016f3d163a91d11602671a0c96d5ec3ae3c7eba898679dd1aa01eae09cc7b65"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc852700b80f631e0c64a5a52e2631cfbfa21ed0af7599ada00f016f6254e223"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitpad"
  desc "Git log & branch manager for the terminal"
  homepage "https://github.com/jinhyo-dev/gitpad"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "gitpad"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitpad"]
    end
  end

  # No zap stanza required
end
