# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitpad" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "556060d917e71f17821e73d5e0cc75855ff2af5a853663a01163ccd0c9ad1386"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "255d1abd6368148f03d44573e182a09212a5c779f1bb7f2fb97ff9c5f58d7b30"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0161fa1c454c5730c2cc1d7b0a244f84ba29e5efc4035657333a9c919e4f029a"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c3807b853ca8db657e7d7e01f565d86cdb7f4bb47e842e9473a61c3261bac168"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitpad"
  desc "Git log & branch manager for the terminal"
  homepage "https://github.com/jinhyo-dev/gitpad"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "gitpad"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitpad"]
    end
  end

  # No zap stanza required
end
