# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitpad" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "d6808492194d32b21f4b75c12dd7df90795ead9ef3ed3046bf6300f229418ed0"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c277bd415bced22c7a13b78441b4a03a3cc8d4adfe2d5ca2bde8ee8fb31b6128"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fa8bb5b795e6e423f69e65c951b79c36e5fe5319b6c65d052e60fd4fb238a8b6"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7355803f915529bbc0993734df5e61f72f012115492553b7f1e519a8d1743296"
      url "https://github.com/jinhyo-dev/gitpad/releases/download/v#{version}/gitpad_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitpad"
  desc "Git log & branch manager for the terminal"
  homepage "https://github.com/jinhyo-dev/gitpad"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "gitpad"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitpad"]
    end
  end

  # No zap stanza required
end
